name: Code Check Before Merge

on:
  pull_request:
    branches:
      - develop
      - staging
      - master
  push:
    branches:
      - develop
      - staging
      - master

jobs:
  phpcs-checker:
    name: PHP CodeSniffer
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download PHP_CodeSniffer
        run: |
          curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
          chmod +x phpcs.phar

      - name: Run PHP_CodeSniffer
        run: php phpcs.phar --standard=phpcs.xml.dist