name: Delete artifacts now

on:
  workflow_dispatch:

permissions:
  actions: read
  contents: read

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Delete all artifacts
        uses: geekyeggo/delete-artifact@v2
        with:
          age: '0 days'
