name: CI/CD Pipeline

on:
  push:
    branches:
      - develop
    tags:
      - '*'

jobs:
  build-php:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Set Build Version
        run: |
          if [ "${{ github.ref }}" == "refs/heads/master" ]; then
            echo "BUILD_VERSION=latest" >> $GITHUB_ENV;
          else
            echo "BUILD_VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV;
          fi

      - name: Build and Push PHP Image
        run: |
          docker build --pull --cache-from ghcr.io/${{ github.repository }}/php:${{ env.BUILD_VERSION }} --file ./docker/Dockerfile --target app-ci -t ghcr.io/${{ github.repository }}/php:${{ github.sha }} .
          docker tag ghcr.io/${{ github.repository }}/php:${{ github.sha }} ghcr.io/${{ github.repository }}/php:${{ env.BUILD_VERSION }}
          docker push ghcr.io/${{ github.repository }}/php:${{ env.BUILD_VERSION }}

  build-nginx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Set Build Version
        run: |
          if [ "${{ github.ref }}" == "refs/heads/master" ]; then
            echo "BUILD_VERSION=latest" >> $GITHUB_ENV;
          else
            echo "BUILD_VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV;
          fi

      - name: Build and Push Nginx Image
        run: |
          docker pull ghcr.io/${{ github.repository }}/nginx:${{ env.BUILD_VERSION }} || true
          docker build --pull --cache-from ghcr.io/${{ github.repository }}/nginx:${{ env.BUILD_VERSION }} --file ./docker/Dockerfile --target web-ci -t ghcr.io/${{ github.repository }}/nginx:${{ github.sha }} .
          docker tag ghcr.io/${{ github.repository }}/nginx:${{ github.sha }} ghcr.io/${{ github.repository }}/nginx:${{ env.BUILD_VERSION }}
          docker push ghcr.io/${{ github.repository }}/nginx:${{ env.BUILD_VERSION }}
