name: CI/CD Pipeline

on:
  push:
    branches:
      - develop
    tags:
      - '*'

env:
  IMAGE_PHP: ghcr.io/${{ github.repository }}/php
  IMAGE_NGINX: ghcr.io/${{ github.repository }}/nginx

jobs:
  get-vendors:
    runs-on: ubuntu-latest
    container: composer
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts --ignore-platform-reqs
      - name: Copy .env file
        run: cp .env.example .env
      - name: Upload vendor
        uses: actions/upload-artifact@v4
        with:
          name: vendor
          path: |
            vendor/
            .env

  build-assets:
    runs-on: ubuntu-latest
    container: node:18-alpine
    needs: get-vendors
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Download vendor
        uses: actions/download-artifact@v4
        with:
          name: vendor
          path: .
      - name: Setup .env
        run: |
          echo "VITE_APP_NAME=Streaming" >> .env
      - name: Install dependencies
        run: npm install
      - name: Build assets
        run: npm run build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: public-build
          path: public/build/

  build-php:
    runs-on: ubuntu-latest
    needs:
      - get-vendors
      - build-assets
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Set Build Version
        run: |
          if [ "${{ github.ref }}" == "refs/heads/master" ]; then
            echo "BUILD_VERSION=latest" >> $GITHUB_ENV;
          else
            echo "BUILD_VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV;
          fi

      - name: Build and Push PHP Image
        run: |
          docker build --pull --cache-from $IMAGE_PHP:${{ env.BUILD_VERSION }} --file ./docker/Dockerfile --target app-ci -t $IMAGE_PHP:${{ github.sha }} .
          docker tag $IMAGE_PHP:${{ github.sha }} $IMAGE_PHP:${{ env.BUILD_VERSION }}
          docker push $IMAGE_PHP:${{ env.BUILD_VERSION }}

  build-nginx:
    runs-on: ubuntu-latest
    needs:
      - get-vendors
      - build-assets
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Set Build Version
        run: |
          if [ "${{ github.ref }}" == "refs/heads/master" ]; then
            echo "BUILD_VERSION=latest" >> $GITHUB_ENV;
          else
            echo "BUILD_VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV;
          fi

      - name: Build and Push Nginx Image
        run: |
          docker pull $IMAGE_NGINX:${{ env.BUILD_VERSION }} || true
          docker build --pull --cache-from $IMAGE_NGINX:${{ env.BUILD_VERSION }} --file ./docker/Dockerfile --target web-ci -t $IMAGE_NGINX:${{ github.sha }} .
          docker tag $IMAGE_NGINX:${{ github.sha }} $IMAGE_NGINX:${{ env.BUILD_VERSION }}
          docker push $IMAGE_NGINX:${{ env.BUILD_VERSION }}
